# Use the official Node.js image as base
FROM node:20 AS base

# Set working directory
WORKDIR /var/www/html

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install Node.js dependencies using Yarn
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose port 5173
EXPOSE 5173

# Start the development server
CMD ["yarn", "dev"]
